language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- nightly

matrix:
  allow_failures:
    - php: nightly

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction

script:
- composer validate --strict
- find src tests -name *.php | xargs -n 1 -P4 php -l
- vendor/bin/phpunit
