language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
# Nightly is now at v8.0.0 which is not supported by a lot of composer packages
# just yet. We should probably wait untill it is more widely accepted.
#- nightly

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction

script:
- composer validate --strict
- find src tests -name *.php | xargs -n 1 -P4 php -l
- vendor/bin/phpunit
